baseURL: https://aylinetravers.com
languageCode: en-us
title: Ayline Travers
theme: portfolio-v1

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: projets
    - name: Projets
    - url: /projets
    - weight: 10
